config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#index'
  get 'index' => 'homes#index'
  get '/details' => 'homes#show'
  get '/father' => 'homes#father_details'
  get '/mother' => 'homes#mother_details'
  get '/children' => 'homes#children_details'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
  has_many :home
   has_one :father
   has_one :mother
   validates :Name, :Aadhar, :Dob, :Father, :Mother, :Children, presence: true

  #attr_reader :Name, :Aadhar, :Dob, :Father, :Mother, :Children
end

app/controllers/application_controller.rb
require 'faker'
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  require 'faker'
  before_action :set_home, only: [:edit, :update, :destroy]

  WillPaginate.per_page = 10
  def index
    @homes = Home.all.paginate(:page => params[:page], :per_page => 10)
  end


  def show
    @home = Home.find_by(id: params[:id])
  end

  def father_details
     @home = Home.find_by(id: params[:id])
  end

  def mother_details
     @home = Home.find_by(id: params[:id])
  end

  def children_details
     @home = Home.find_by(id: params[:id])
  end
  def new
    @home = Home.new
  end

  def create
    @home = user
      if @home.save
         redirect_to @home, notice: 'user was successfully created.'
      end
  end

  def edit
  end

  private
    def set_home
      @home = Home.find(params[:id])
    end

    def home_params
      params.require(:home).permit(:index, :Name, :Aadhar, :Dob, :Father, :Mother, :Children)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="field">
    <%= form.label :Aadhar %>
    <%= form.number_field :Aadhar %>
  </div>

  <div class="field">
    <%= form.label :Dob %>
    <%= form.number_field :Dob %>
  </div>

  <div class="field">
    <%= form.label :Father %>
    <%= form.text_field :Father %>
  </div>

  <div class="field">
    <%= form.label :Mother %>
    <%= form.text_field :Mother %>
  </div>

  <div class="field">
    <%= form.label :Children %>
    <%= form.text_field :Children %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/children_details.html.erb
<h1>Children Deatils</h1>
  <tbody>
      <tr>
        <td><p>
          <strong>Name:</strong>
          <%= @home.Children %>
        </p></td>

        <td><p>
          <strong>Aadhar:22200002</strong>

        </p></td>

        <td><p>
          <strong>Dob:13/12/1997</strong>

        </p></td>
      </tbody>
      <%= link_to 'Back', root_path %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/father_details.html.erb
<h1>Father Deatils</h1>
  <tbody>
      <tr>
        <td><p>
          <strong>Name:</strong>
          <%= @home.Father %>
        </p></td>

        <td><p>
          <strong>Aadhar: 1001111</strong>

        </p></td>

        <td><p>
          <strong>Dob: 17/12/1985</strong>

        </p></td>
      </tbody>

      <%= link_to 'Back', root_path %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Index</h1>
  <tbody>
    <% @homes.presence && @homes.each do |home| %>
      <tr>
        <td><p>
          <strong>Name:</strong>
          <%= home.Name %>
        </p></td>

        <td><p>
          <strong>Aadhar:</strong>
          <%= home.Aadhar %>
        </p></td>

        <td><p>
          <strong>Dob:</strong>
          <%= home.Dob %>
        </p></td>

        <p>
          <strong>Father:</strong>
          <%= home.Father %>
           <%= link_to 'Show Details', father_path(id:home.id) %>

        </p>

        <p>
          <strong>Mother:</strong>
          <%= home.Mother %>
          <%= link_to 'Show Details', mother_path(id:home.id) %>
        </p>

        <p>
          <strong>Children:</strong>
          <%= home.Children %>
          <%= link_to 'Show Details', children_path(id:home.id) %>

        </p>

        <div class="center">
          <%= will_paginate @home %>
        </div>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/homes/mother_details.html.erb
<h1>Mother Deatils</h1>
  <tbody>
      <tr>
        <td><p>
          <strong>Name:</strong>
          <%= @home.Mother %>
        </p></td>

        <td><p>
          <strong>Aadhar:1000022</strong>

        </p></td>

        <td><p>
          <strong>Dob:12/12/1988</strong>

        </p></td>
      </tbody>
      <%= link_to 'Back', root_path %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @home.Name %>
</p>

<p>
  <strong>Aadhar:</strong>
  <%= @home.Aadhar %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @home.Dob %>
</p>

<p>
  <strong>Father:</strong>
  <%= @home.Father %>
</p>

<p>
  <strong>Mother:</strong>
  <%= @home.Mother %>
</p>

<p>
  <strong>Children:</strong>
  <%= @home.Children %>
</p>


<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hindustani</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>